
# load Neonic data ----

all_Neo_data = read.csv2("Data/Doeringetal_2026_Neonics.csv", stringsAsFactors = T, fileEncoding = "latin1")

# remove columns that are not used in the analysis ----

# delete all columns with only one value (in most cases "NA", "yes", or "no")
new_Neo_data = Filter(function(x)(length(unique(x))>1), all_Neo_data)

# transform factors into numerics/characters ----

new_Neo_data$c_unit = as.character(new_Neo_data$c_unit)
new_Neo_data$t_unit = as.character(new_Neo_data$t_unit)
new_Neo_data$c_n_replicates = as.integer(new_Neo_data$c_n_replicates)
new_Neo_data$t_n_replicates = as.integer(new_Neo_data$t_n_replicates)
new_Neo_data$c_mean = as.numeric(levels(new_Neo_data$c_mean))[new_Neo_data$c_mean]
new_Neo_data$t_mean = as.numeric(levels(new_Neo_data$t_mean))[new_Neo_data$t_mean]
new_Neo_data$c_SD = as.numeric(levels(new_Neo_data$c_SD))[new_Neo_data$c_SD]
new_Neo_data$t_SD = as.numeric(levels(new_Neo_data$t_SD))[new_Neo_data$t_SD]
new_Neo_data$c_SE = as.numeric(levels(new_Neo_data$c_SE))[new_Neo_data$c_SE]
new_Neo_data$t_SE = as.numeric(levels(new_Neo_data$t_SE))[new_Neo_data$t_SE]
new_Neo_data$measured_dose_mass = as.numeric(levels(new_Neo_data$measured_dose_mass))[new_Neo_data$measured_dose_mass]
new_Neo_data$nominal_dose_mass = as.numeric(levels(new_Neo_data$nominal_dose_mass))[new_Neo_data$nominal_dose_mass]
new_Neo_data$nominal_dose_mass_units = as.character(new_Neo_data$nominal_dose_mass_units)
new_Neo_data$measured_dose_mass_units = as.character(new_Neo_data$measured_dose_mass_units)

# extract data generated by a "contact test" ----

Neonics_contact_test = subset(new_Neo_data, exposure_route == "contact_test")
Neonics_in_sediment = subset(new_Neo_data, exposure_route == "sediment")
new_Neo_data = Neonics_in_sediment # Only use Neonics in soil

# remove data points generated after a recovery period ----
# 84 data points removed
new_Neo_data = subset(new_Neo_data, recovery_duration == 0)

# unify units ----

# Transform "µmol/g_protein" in "nmol/mg_protein"
new_Neo_data[new_Neo_data == "µmol/g_protein"] = "nmol/mg_protein"

# Transform "µmol/min/mg_protein" in "U/mg_protein"
new_Neo_data[new_Neo_data == "µmol/min/mg_protein"] = "U/mg_protein"

# Transform "mmol/mg_protein" in "nmol/mg_protein"
temporary_data = subset(new_Neo_data, t_unit == "mmol/mg_protein")
temporary_data2 = subset(new_Neo_data, t_unit != "mmol/mg_protein")
temporary_data$c_mean = temporary_data$c_mean*1000000
temporary_data$c_SD = temporary_data$c_SD*1000000
temporary_data$c_SE = temporary_data$c_SE*1000000
temporary_data$t_mean = temporary_data$t_mean*1000000
temporary_data$t_SD = temporary_data$t_SD*1000000
temporary_data$t_SE = temporary_data$t_SE*1000000
temporary_data[temporary_data == "mmol/mg_protein"] = "nmol/mg_protein"
new_Neo_data = rbind(temporary_data, temporary_data2)

# Transform "U/g_protein" in "U/mg_protein"
temporary_data = subset(new_Neo_data, t_unit == "U/g_protein")
temporary_data2 = subset(new_Neo_data, t_unit != "U/g_protein")
temporary_data$c_mean = temporary_data$c_mean/1000
temporary_data$c_SD = temporary_data$c_SD/1000
temporary_data$c_SE = temporary_data$c_SE/1000
temporary_data$t_mean = temporary_data$t_mean/1000
temporary_data$t_SD = temporary_data$t_SD/1000
temporary_data$t_SE = temporary_data$t_SE/1000
temporary_data[temporary_data == "U/g_protein"] = "U/mg_protein"
new_Neo_data = rbind(temporary_data, temporary_data2)

# Transform "U/µg_protein" in "U/mg_protein"
temporary_data = subset(new_Neo_data, t_unit == "U/µg_protein")
temporary_data2 = subset(new_Neo_data, t_unit != "U/µg_protein")
temporary_data$c_mean = temporary_data$c_mean*1000
temporary_data$c_SD = temporary_data$c_SD*1000
temporary_data$c_SE = temporary_data$c_SE*1000
temporary_data$t_mean = temporary_data$t_mean*1000
temporary_data$t_SD = temporary_data$t_SD*1000
temporary_data$t_SE = temporary_data$t_SE*1000
temporary_data[temporary_data == "U/µg_protein"] = "U/mg_protein"
new_Neo_data = rbind(temporary_data, temporary_data2)

# Transform "nmol/min/mg_protein" in "U/mg_protein"
temporary_data = subset(new_Neo_data, t_unit == "nmol/min/mg_protein")
temporary_data2 = subset(new_Neo_data, t_unit != "nmol/min/mg_protein")
temporary_data$c_mean = temporary_data$c_mean/1000
temporary_data$c_SD = temporary_data$c_SD/1000
temporary_data$c_SE = temporary_data$c_SE/1000
temporary_data$t_mean = temporary_data$t_mean/1000
temporary_data$t_SD = temporary_data$t_SD/1000
temporary_data$t_SE = temporary_data$t_SE/1000
temporary_data[temporary_data == "nmol/min/mg_protein"] = "U/mg_protein"
new_Neo_data = rbind(temporary_data, temporary_data2)

# Transform "mmol/min/mg_protein" in "U/mg_protein"
temporary_data = subset(new_Neo_data, t_unit == "mmol/min/mg_protein")
temporary_data2 = subset(new_Neo_data, t_unit != "mmol/min/mg_protein")
temporary_data$c_mean = temporary_data$c_mean*1000
temporary_data$c_SD = temporary_data$c_SD*1000
temporary_data$c_SE = temporary_data$c_SE*1000
temporary_data$t_mean = temporary_data$t_mean*1000
temporary_data$t_SD = temporary_data$t_SD*1000
temporary_data$t_SE = temporary_data$t_SE*1000
temporary_data[temporary_data == "mmol/min/mg_protein"] = "U/mg_protein"
new_Neo_data = rbind(temporary_data, temporary_data2)

# Transform "ng/mg_protein" of Glutathione (307,33 g*mol−1) in "nmol/mg_protein"
temporary_data = subset(new_Neo_data, endpoint == "Glutathione Concentration")
temporary_data2 = subset(new_Neo_data, endpoint != "Glutathione Concentration")
temporary_data3 = subset(temporary_data, t_unit == "ng/mg_protein")
temporary_data4 = subset(temporary_data, t_unit != "ng/mg_protein")
temporary_data3$c_mean = (temporary_data3$c_mean/(307.33))
temporary_data3$c_SD = (temporary_data3$c_SD/(307.33))
temporary_data3$c_SE = (temporary_data3$c_SE/(307.33))
temporary_data3$t_mean = (temporary_data3$t_mean/(307.33))
temporary_data3$t_SD = (temporary_data3$t_SD/(307.33))
temporary_data3$t_SE = (temporary_data3$t_SE/(307.33))
temporary_data3[temporary_data3 == "ng/mg_protein"] = "nmol/mg_protein"
new_Neo_data = rbind(temporary_data2, temporary_data3, temporary_data4)

# Transform "relative_fluorescence" in "fold_change"
new_Neo_data[new_Neo_data == "relative_fluorescence"] = "fold_change"

# Transform "Thiobarbituric Acid Reactive Species" in "Malondialdehyde Concentration", 
# because the concentration of the same product is measured (see Buege & Aust 1978, Methods in Enzymology)
new_Neo_data[new_Neo_data == "Thiobarbituric Acid Reactive Species"] = "Malondialdehyde Concentration"

# Transform "Glutathione peroxide activity" in "Peroxide activity"
new_Neo_data[new_Neo_data == "Glutathione Peroxidase Activity"] = "Peroxidase Activity"

# Transform "µg/kg" in "mg/kg"
temporary_data = subset(new_Neo_data, nominal_dose_mass_units == "µg/kg")
temporary_data2 = subset(new_Neo_data, nominal_dose_mass_units != "µg/kg")
temporary_data3 = new_Neo_data[is.na(new_Neo_data$nominal_dose_mass_units),]
temporary_data$nominal_dose_mass = temporary_data$nominal_dose_mass/1000
temporary_data[temporary_data == "µg/kg"] = "mg/kg"
new_Neo_data = rbind(temporary_data, temporary_data2, temporary_data3)

# Transform "mg/kg" in "% w w-1"
new_Neo_data$nominal_dose_mass = new_Neo_data$nominal_dose_mass/10000
new_Neo_data$measured_dose_mass = new_Neo_data$measured_dose_mass/10000
new_Neo_data[new_Neo_data == "mg/kg"] = "% w w-1"

# Combine measured and nominal particle concentration in one column
# 18 data points are excluded here, since the amount of Neonic could not be determined exactly (<1.69 µg/L)
new_Neo_data["combined_concentration"] = new_Neo_data$measured_dose_mass
new_Neo_data["combined_concentration_unit"] = "% w w-1"
temporary_data = subset(new_Neo_data, nominal_dose_mass != "NA" &  is.na(new_Neo_data$measured_dose_mass))
temporary_data2 = subset(new_Neo_data, measured_dose_mass != "NA")

temporary_data["combined_concentration"] = temporary_data$nominal_dose_mass
new_Neo_data = rbind(temporary_data, temporary_data2)
new_Neo_data$log_combined_concentration = log(new_Neo_data$combined_concentration)

# Abbreviate ROS marker
new_Neo_data$endpoint = as.character(new_Neo_data$endpoint)
new_Neo_data[new_Neo_data == "Reactive Oxygen Species Production"] = "ROS"
new_Neo_data[new_Neo_data == "Catalase Activity"] = "CAT"
new_Neo_data[new_Neo_data == "Superoxide Dismutase Activity"] = "SOD"
new_Neo_data[new_Neo_data == "Glutathione S-Transferase Activity"] = "GST"
new_Neo_data[new_Neo_data == "Malondialdehyde Concentration"] = "MDA"
new_Neo_data[new_Neo_data == "Peroxidase Activity"] = "POD"
new_Neo_data[new_Neo_data == "Protein Carbonyl Concentration"] = "PC"
new_Neo_data[new_Neo_data == "Carboxylesterase activity"] = "CarE"
new_Neo_data[new_Neo_data == "sod mRNA expression"] = "SOD mRNA expression"
new_Neo_data[new_Neo_data == "Catalase mRNA expression"] = "CAT mRNA expression"
new_Neo_data[new_Neo_data == "Glutathione Concentration"] = "GSH"
new_Neo_data[new_Neo_data == "Glutathione Reductase Activity"] = "GR"
new_Neo_data[new_Neo_data == "8-OHdG Concentration"] = "8-OHdG"
new_Neo_data[new_Neo_data == "Hydroxyl radical levels"] = "OH"
new_Neo_data[new_Neo_data == "Glutathione S-Transferase mRNA expression"] = "GST mRNA expression"
new_Neo_data$endpoint = as.factor(new_Neo_data$endpoint)

# Delete temporary data
rm(temporary_data, temporary_data2, temporary_data3, temporary_data4)

# Overview
table(new_Neo_data$t_unit,new_Neo_data$endpoint)

# export prepared data ----
write.csv2(new_Neo_data, "Data/new_Neonics_data.csv", row.names = FALSE)
write.csv2(Neonics_contact_test, "Data/Neonics_contact_test.csv", row.names = FALSE)

